[package]
name = "magicore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
common = { path = "../common" }
nanorand = "0.7.0"
thiserror = "1.0.50"
