[package]
name = "lack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.25.0"
rayon = "1.8.0"
thiserror = "1.0.56"
vec_map = "0.8.2"
