[package]
name = "planiscope"
version = "0.1.0"
edition = "2021"

[dependencies]
fidget = { git = "https://github.com/johnbchron/fidget", rev = "ca8e0b0", default-features = false, features = ["mesh", "rhai"] }
glam = "0.24.0"
serde = { version = "1.0.188", features = ["derive"] }
